version: '3'
services:
  postgres:
    container_name: 'postgres'
    image: postgres:15
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    networks:
      - backend
  gateway:
    container_name: "gateway"
    hostname: gateway
    build: ./gateway
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - backend
  user:
    container_name: "user"
    hostname: user
    build: ./user
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend
  document:
    container_name: "document"
    hostname: document
    build: ./document
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend


networks:
  backend:
    driver: bridge